[WIP] Analytics for each page
hack4impact-uiuc/uiuc.hack4impact.org pull request #1
Opened 2019-07-30 00:40 UTC by choiboy98

All pages work except for the Apply page.
Apply page does not seem to work because it does not have a class on its own. I could not figure out how to add Google Analytics code to the const function.

The new google analytics is done with uiuc@hack4impact.org email.

2019-08-03 02:17 UTC, angadgarg25 commented on components/Analytics.js
> +    //ReactGA.pageview(window.location.pathname + window.location.search);
lets remove this?

2019-08-03 02:23 UTC, angadgarg25 requested changes
Mostly nits. I'll take a look at fixing apply page today. Also could you remove  `logEvent` from your imports for now? As far as I can tell, we don't currently use it yet, once we want to use it we can add it back in.

2019-08-03 02:23 UTC, angadgarg25 commented on components/Analytics.js
> +    //ReactGA.pageview(window.location.pathname + window.location.search);
lets remove this comment

2019-08-03 02:23 UTC, angadgarg25 commented on pages/_app.js
> +    // logPage()
remove comments

2019-08-03 02:23 UTC, angadgarg25 commented on pages/_app.js
> +    // logPage()
and remove the imports for these if they're not used anywhere else in this file

2019-08-03 02:23 UTC, angadgarg25 commented on pages/index.js
> +
remove empty line

2019-08-03 05:01 UTC, angadgarg25 commented on pages/apply/index.js
>  const ApplyPage = () => (
this is a short hand way to define react components, so you can't define `componentDidMount`. Assuming thats why you couldn't add google analytics, all you have to do is convert this to look like a regular component.
`class ApplyPage extends React.Component {` and then move the jsx code to be returned by a render function.

2019-08-07 04:27 UTC, angadgarg25 submitted a review, later dismissed
🐓

2019-08-07 04:38 UTC, rgychiu approved these changes
Looks good to me based on Angad's previous comments as well

2019-08-07 04:53 UTC, merged